### ISSUE TITLE
i18nStore.ts 中直接 import Vue from 'vue' 在 vue3  中不兼容

### ISSUE THREAD

**Issue by yeli19950109** [x-extends/vxe-core#1]
[packages/src/i18nStore.ts](https://github.com/x-extends/vxe-core/blob/main/packages/src/i18nStore.ts)

vue3 没有 default 导出

推荐换成vue-demi

**Comment by haohaitao** [comment]
我也遇到了这个问题
"version": "4.0.14",
已提交修复pr
